##sparql --results=CSV --data=../resources/be/vlaanderen/omgeving/data/id/conceptscheme/fysico-chemisch/fysico-chemisch.ttl  --query rdf_to_csv.rq > ../resources/be/vlaanderen/omgeving/data/id/conceptscheme/fysico-chemisch/fysico-chemisch2.csv


prefix skos:  <http://www.w3.org/2004/02/skos/core#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix dcat:   <http://www.w3.org/ns/dcat#>
prefix cs:    <https://data.vlaanderen.be/ns/chemische_stof#>

select distinct
?type
?uri
?vmmParameterId
?notation
?prefLabel
?inScheme
?topConceptOf
?theme
?collection
where 
{?uri
a ?type .
optional {?uri skos:definition ?definition }
optional {?uri skos:inScheme ?inScheme }
optional {?uri skos:notation ?notation }
optional {?uri skos:prefLabel ?prefLabel }
optional {?uri dcat:theme ?theme .}
optional {?uri cs:vmmParameterId ?vmmParameterId }
optional {?uri skos:topConceptOf ?topConceptOf .}
optional {?uri a skos:Concept . ?collection skos:member ?uri .}
}
ORDER BY ?uri

